INSERT INTO public.medicamentos (nome, acao_principal) VALUES
  ('LOSARTANA', 'Controle da Pressão Arterial'),
  ('ENALAPRIL', 'Controle da Pressão Arterial'),
  ('CAPTOPRIL', 'Controle da Pressão Arterial'),
  ('HIDROCLOROTIAZIDA', 'Diurético / Controle da Pressão'),
  ('AMLODIPINO', 'Controle da Pressão Arterial'),
  ('PROPRANOLOL', 'Controle da Pressão Arterial'),
  ('ESPIRONOLACTONA', 'Diurético / Controle da Pressão'),
  ('FUROSEMIDA', 'Diurético / Controle da Pressão'),
  ('CARVEDILOL', 'Diurético / Controle da Pressão'),
  ('GLIBENCLAMIDA', 'Controle do Diabetes'),
  ('GLICLAZIDA', 'Controle do Diabetes'),
  ('DAPAGLIFLOZINA', 'Controle do Diabetes'),
  ('EMPAGLIFLOZINA', 'Controle do Diabetes'),
  ('INSULINA', 'Controle do Diabetes (Insulina)'),
  ('ATORVASTATINA', 'Controle de Colesterol'),
  ('ROSUVASTATINA', 'Controle de Colesterol'),
  ('EZETIMIBA', 'Controle de Colesterol'),
  ('PANTOPRAZOL', 'Protetor Gástrico / Refluxo'),
  ('ESOMEPRAZOL', 'Protetor Gástrico / Refluxo'),
  ('LANSOPRAZOL', 'Protetor Gástrico / Refluxo'),
  ('LEVOTIROXINA', 'Hormônio Tireoidiano (Hipotireoidismo)'),
  ('CLONAZEPAM', 'Calmante / Ansiolítico'),
  ('DIAZEPAM', 'Calmante / Ansiolítico'),
  ('ALPRAZOLAM', 'Calmante / Ansiolítico'),
  ('BROMAZEPAM', 'Calmante / Ansiolítico'),
  ('LORAZEPAM', 'Calmante / Ansiolítico'),
  ('ZOLPIDEM', 'Calmante / Ansiolítico / Indutor de Sono'),
  ('ESCITALOPRAM', 'Antidepressivo'),
  ('FLUOXETINA', 'Antidepressivo'),
  ('SERTRALINA', 'Antidepressivo'),
  ('AMITRIPTILINA', 'Antidepressivo / Dor Crônica'),
  ('CITALOPRAM', 'Antidepressivo'),
  ('VENLAFAXINA', 'Antidepressivo'),
  ('DESVENLAFAXINA', 'Antidepressivo'),
  ('BUPROPIONA', 'Antidepressivo'),
  ('DIPIRONA', 'Analgésico / Antitérmico'),
  ('PARACETAMOL', 'Analgésico / Antitérmico'),
  ('IBUPROFENO', 'Anti-inflamatório / Analgésico'),
  ('NIMESULIDA', 'Anti-inflamatório'),
  ('DICLOFENACO', 'Anti-inflamatório'),
  ('CETOPROFENO', 'Anti-inflamatório'),
  ('MELOXICAM', 'Anti-inflamatório'),
  ('TRAMADOL', 'Analgésico Opioide'),
  ('CODEÍNA', 'Analgésico Opioide'),
  ('DORFLEX', 'Anti-inflamatório / Analgésico / Relaxante Muscular'),
  ('TORSILAX', 'Relaxante Muscular / Analgésico'),
  ('CICLOBENZAPRINA', 'Relaxante Muscular'),
  ('RIVAROXABANA', 'Anticoagulante'),
  ('APIXABANA', 'Anticoagulante'),
  ('AAS (ÁCIDO ACETILSALICÍLICO)', 'Anticoagulante / Analgésico'),
  ('CLOPIDOGREL', 'Antiplaquetário'),
  ('AMOXICILINA', 'Antibiótico'),
  ('AZITROMICINA', 'Antibiótico'),
  ('CEFALEXINA', 'Antibiótico'),
  ('CIPROFLOXACINO', 'Antibiótico'),
  ('LEVOFLOXACINO', 'Antibiótico'),
  ('LORATADINA', 'Antialérgico'),
  ('DEXCLORFENIRAMINA', 'Antialérgico'),
  ('FEXOFENADINA', 'Antialérgico'),
  ('DESLORATADINA', 'Antialérgico'),
  ('PREDNISONA', 'Corticoide / Anti-inflamatório'),
  ('DEXAMETASONA', 'Corticoide / Anti-inflamatório'),
  ('HIDROCORTISONA', 'Corticoide / Anti-inflamatório'),
  ('CARBAMAZEPINA', 'Anticonvulsivante'),
  ('PREGABALINA', 'Anticonvulsivante / Dor Neuropática'),
  ('GABAPENTINA', 'Anticonvulsivante / Dor Neuropática'),
  ('ÁCIDO VALPROICO', 'Anticonvulsivante / Estabilizador de Humor'),
  ('TOPIRAMATO', 'Anticonvulsivante / Prevenção de Enxaqueca'),
  ('FENITOÍNA', 'Anticonvulsivante'),
  ('PIRACETAM', 'Anticonvulsivante / Nootrópico'),
  ('QUETIAPINA', 'Antipsicótico / Estabilizador de Humor'),
  ('RISPERIDONA', 'Antipsicótico'),
  ('OLANZAPINA', 'Antipsicótico')
ON CONFLICT (nome) DO NOTHING;
